# .github/workflows/snake.yml
name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
  # Also run on every push on the main branch
  push:
    branches:
    - main

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4 # Updated to v4 for better stability
        with:
            # We need full permissions for the commit step later
            fetch-depth: 0 
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: maaz-khalid # Hardcoded username for reliability
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
      - name: Push new files to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output # Target branch for the generated files
          message: 'Update snake animations'
          add: 'dist/' # Commits the whole 'dist' folder
